2022-02-15 18:36:16,805 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 18:36:16,836 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 18:36:16,836 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 18:36:16,836 : DHP.Utils.logger : DEBUG : Entering sign_up module
2022-02-15 18:36:28,169 : DHP.Utils.logger : ERROR : name 'q2_insert' is not defined
Traceback (most recent call last):
  File "d:\Sindhi Model School (SMS)\HARSH\PROGRAMS\DataHandlingProject\Project-Mysql-library\DHP\users\register.py", line 47, in sign_up
    q2_insert
NameError: name 'q2_insert' is not defined
2022-02-15 18:38:30,793 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 18:38:30,816 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 18:38:30,816 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 18:38:30,816 : DHP.Utils.logger : DEBUG : Entering sign_up module
2022-02-15 18:38:34,320 : DHP.Utils.logger : ERROR : name 'WARN' is not defined
Traceback (most recent call last):
  File "d:\Sindhi Model School (SMS)\HARSH\PROGRAMS\DataHandlingProject\Project-Mysql-library\DHP\users\register.py", line 17, in sign_up
    WARN("PLEASE ENTER ONLY 4 DIGIT ID!!! (No Less No More)")
NameError: name 'WARN' is not defined
2022-02-15 18:38:51,550 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 18:38:51,565 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 18:38:51,565 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 18:38:51,565 : DHP.Utils.logger : DEBUG : Entering sign_up module
2022-02-15 18:38:59,283 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 18:38:59,288 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 18:38:59,288 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 18:38:59,288 : DHP.Utils.logger : DEBUG : Entering sign_up module
2022-02-15 21:30:53,156 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 21:30:53,281 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 21:30:53,281 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 21:31:09,502 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 21:31:09,507 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 21:31:09,507 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 21:49:04,137 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 21:49:04,145 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 21:49:04,145 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 21:49:15,332 : DHP.Utils.logger : INFO : Super User 5940 has Logged In! Power: 3
2022-02-15 21:56:51,674 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 21:56:51,694 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 21:56:51,694 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 21:57:01,591 : DHP.Utils.logger : INFO : Super User 5940 has Logged In! Power: 3
2022-02-15 21:57:01,623 : DHP.Utils.logger : ERROR : name 'color' is not defined
Traceback (most recent call last):
  File "d:\Sindhi Model School (SMS)\HARSH\PROGRAMS\DataHandlingProject\Project-Mysql-library\DHP\users\adminlogin.py", line 32, in admin_login
    color(f"Super User {id1} has Logged In! Power: {power}")
NameError: name 'color' is not defined
2022-02-15 21:59:08,285 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 21:59:08,299 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 21:59:08,300 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 21:59:13,189 : DHP.Utils.logger : ERROR : list index out of range
Traceback (most recent call last):
  File "d:\Sindhi Model School (SMS)\HARSH\PROGRAMS\DataHandlingProject\Project-Mysql-library\DHP\users\adminlogin.py", line 21, in admin_login
    power = power[3]
IndexError: list index out of range
2022-02-15 22:01:05,047 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 22:01:05,059 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 22:01:05,059 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 22:02:45,343 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 22:02:45,353 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 22:02:45,353 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 22:07:57,518 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-15 22:07:57,529 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-15 22:07:57,530 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-15 22:08:03,548 : DHP.Utils.logger : INFO : Super User 5940 has Logged In! Power: 3
2022-02-15 22:08:03,574 : DHP.Utils.logger : ERROR : name 'color' is not defined
Traceback (most recent call last):
  File "d:\Sindhi Model School (SMS)\HARSH\PROGRAMS\DataHandlingProject\Project-Mysql-library\DHP\users\adminlogin.py", line 29, in admin_login
    color(f"Super User {id1} has Logged In! Power: {power}")
NameError: name 'color' is not defined
2022-02-19 16:47:11,685 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-19 16:47:11,711 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-19 16:47:11,711 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-19 16:47:23,629 : DHP.Utils.logger : ERROR : name 'name' is not defined
Traceback (most recent call last):
  File "d:\Sindhi Model School (SMS)\HARSH\PROGRAMS\DataHandlingProject\Project-Mysql-library\DHP\sudo\admin.py", line 33, in add_admin
    q2_value = (id1, name, passwd)
NameError: name 'name' is not defined
2022-02-19 16:47:50,873 : DHP.Utils.logger : WARNING : remove Admin - Loop closed due to Keyboard interrupt Error
2022-02-19 16:49:08,524 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-19 16:49:08,527 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-19 16:49:08,527 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-19 16:49:24,441 : DHP.Utils.logger : ERROR : name 'color' is not defined
Traceback (most recent call last):
  File "d:\Sindhi Model School (SMS)\HARSH\PROGRAMS\DataHandlingProject\Project-Mysql-library\DHP\sudo\admin.py", line 36, in add_admin
    print(color("New User Has Been Created Successfully !!"))
NameError: name 'color' is not defined
2022-02-19 16:49:48,371 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-19 16:49:48,375 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-19 16:49:48,375 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
----
2022-02-19 16:54:32,698 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-02-19 16:54:32,704 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-19 16:54:32,704 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-02-19 16:54:42,362 : DHP.Utils.logger : WARNING : New Admin Added 1111 | By 5940
2022-02-19 16:54:45,029 : DHP.Utils.logger : WARNING : New Admin Added 1111 | By 5940
2022-02-20 17:29:35,740 : Utility : DEBUG : Connected To DataBase | sys
2022-02-20 17:29:35,787 : Utility : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-02-20 17:29:35,788 : Utility : INFO : DB Changed | sys => schoolmysqlproject
2022-02-20 17:29:37,111 : Utility : WARNING : Add Admin - Loop closed due to Keyboard interrupt Error
2022-02-20 17:29:39,080 : Utility : WARNING : remove Admin - Loop closed due to Keyboard interrupt Error
2022-04-29 09:45:48,786 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-04-29 09:45:48,870 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-04-29 09:45:48,870 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-04-29 09:46:15,033 : DHP.Utils.logger : WARNING : New Admin Added 6 | By 5940
2022-04-29 09:46:17,328 : DHP.Utils.logger : WARNING : New Admin Added 6 | By 5940
2022-04-29 09:55:49,097 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-04-29 09:55:49,100 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-04-29 09:55:49,100 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-04-29 09:55:49,111 : DHP.Utils.logger : ERROR : name 'nput' is not defined
Traceback (most recent call last):
  File "D:\Sindhi Model School (SMS)\HARSH\PROGRAMS\DataHandlingProject\Project-Mysql-library\DHP\sudo\admin.py", line 12, in add_admin
    id1 = nput("PLEASE ENTER A 4 DIGIT ID!!! (No Less No More): ")
NameError: name 'nput' is not defined
2022-04-29 09:56:08,633 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-04-29 09:56:08,638 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-04-29 09:56:08,638 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-04-29 09:49:54,030 : DHP.Utils.logger : DEBUG : Connected To DataBase | sys
2022-04-29 09:49:54,034 : DHP.Utils.logger : DEBUG : INITIALIZATION OF DATABASE COMPLETE
2022-04-29 09:49:54,034 : DHP.Utils.logger : INFO : DB Changed | sys => schoolmysqlproject
2022-04-29 09:50:01,412 : DHP.Utils.logger : ERROR : 1366 (HY000): Incorrect integer value: 'a' for column 'user_id' at row 1
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\mysql\connector\connection_cext.py", line 535, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: Incorrect integer value: 'a' for column 'user_id' at row 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sindhi Model School (SMS)\HARSH\PROGRAMS\DataHandlingProject\Project-Mysql-library\DHP\sudo\admin.py", line 39, in add_admin
    cursor.execute(q2_insert, q2_value)
  File "C:\Python\lib\site-packages\mysql\connector\cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "C:\Python\lib\site-packages\mysql\connector\connection_cext.py", line 540, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.DatabaseError: 1366 (HY000): Incorrect integer value: 'a' for column 'user_id' at row 1
